obj-y += zstd_compress.o
obj-y += zstd_decompress.o

ccflags-y += -O3

obj-y := fse_compress.o huf_compress.o compress.o \
		   entropy_common.o fse_decompress.o zstd_common.o \
     huf_decompress.o decompress.o
